### ISSUE TITLE
github workflow

### ISSUE THREAD

**Issue by sahu04** [sahu04/zapscan#3]

**Comment by sahu04** [comment]
**Requirement** - aiTest-UI GitHub Workflow

1. Create a pipeline for dev environment and prod environment.
2. GitHub Actions workflow triggers a build and push to the Amazon ECR repository for the develop environment only when changes are made to the Dockerfile or the package.json file.
3.  GitHub Actions workflow triggers when changes are made to the Dockerfile or package.json file in the production (master) environment. It pulls the "dev" tagged image from ECR, tags it as "Prod," and pushes it to the ECR repository.
4. GitHub Actions workflow deploys to the dev environment on the develop branch and prod environment on the master branch. It executes npm run deploy-dev for development and npm run deploy-prod for production, syncing build directories to designated S3 buckets and creating CloudFront invalidations.

 **prerequisite**
1. Ensure Dockerfile is present.
2. AWS Access Key and Secret Key.
3. Set up an ECR repository.
4.  Ensure the existence of  S3 buckets for both dev and prod environments, along with corresponding CDN distributions for each environment.

**Approach**

1.Make a Dockerfile and check it works by testing it locally.
2. Make a repository in Amazon ECR to store  Docker images securely.
3.Develop a GitHub workflow to automate building and deploying Docker images.


**Task** 
- [ ] Create Dockerfile and test locally.
- [ ] ECR repository
- [ ] GitHub workflow 
-  stages 
- [ ] Build-dev-image
- [ ] Build-prod-image
- [ ] deploy-dev
- [ ] deploy-prod
